name: MedusaDart
version: 0.0.1
description: An absolute bare-bones web app.
homepage: http://threedart.github.com/three.dart/
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  http: any
  http_server: any
  mongo_dart: any
  stats:
    git: git://github.com/Dartist/stats.dart.git
  three:
    git: https://github.com/threeDart/three.dart.git
